volumes:
  thats-my-idea-postgres-data:
    driver: local

services:
  postgres:
    image: postgres
    container_name: thats-my-idea-postgres
    volumes:
      - thats-my-idea-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=thats_my_idea_database
